### ISSUE TITLE
Error in running decoding_nmt.py

### ISSUE THREAD

**Issue by ShivprasadSagare** [AI4Bharat/indic-bart#8]
Following error occurs on running the command as stated here https://github.com/AI4Bharat/indic-bart/blob/main/README.md#decoding-command
```
Traceback (most recent call last):
  File "decode_nmt.py", line 510, in <module>
    run_demo()
  File "decode_nmt.py", line 506, in run_demo
    mp.spawn(model_create_load_decode, nprocs=args.gpus, args=(args,))         #
  File "/home2/shivprasad.sagare/miniconda3/envs/indicbart/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home2/shivprasad.sagare/miniconda3/envs/indicbart/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home2/shivprasad.sagare/miniconda3/envs/indicbart/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home2/shivprasad.sagare/miniconda3/envs/indicbart/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home2/shivprasad.sagare/stuff/copernicus/indicbart/yanmtt/decode_nmt.py", line 171, in model_create_load_decode
    translations = model.module.generate(input_ids.to(gpu), use_cache=True, num_beams=args.beam_size, max_length=int((len(input_ids[0])*args.max_decode_length_multiplier) if args.max_decode_length_multiplier > 0 else -args.max_decode_length_multiplier), min_length=int((len(input_ids[0])*args.min_decode_length_multiplier) if args.min_decode_length_multiplier > 0 else -args.min_decode_length_multiplier), early_stopping=True, attention_mask=input_masks.to(gpu), pad_token_id=tok.pad_token_id, eos_token_id=tok(["</s>"], add_special_tokens=False).input_ids[0][0], decoder_start_token_id=tok([args.tlang if args.use_official_pretrained else "<2"+args.tlang+">"], add_special_tokens=False).input_ids[0][0], bos_token_id=tok(["<s>"], add_special_tokens=False).input_ids[0][0], length_penalty=args.length_penalty, repetition_penalty=args.repetition_penalty, encoder_no_repeat_ngram_size=args.encoder_no_repeat_ngram_size, no_repeat_ngram_size=args.no_repeat_ngram_size, num_return_sequences=args.beam_size if args.return_all_sequences else 1, additional_input_ids=input_ids_parent.to(gpu) if args.multi_source else None, additional_input_ids_mask=input_masks_parent.to(gpu) if args.multi_source else None) ## We translate the batch.
  File "/home2/shivprasad.sagare/miniconda3/envs/indicbart/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/home2/shivprasad.sagare/miniconda3/envs/indicbart/lib/python3.6/site-packages/transformers/generation_utils.py", line 847, in generate
    model_kwargs = self._prepare_encoder_decoder_kwargs_for_generation(input_ids, model_kwargs)
  File "/home2/shivprasad.sagare/miniconda3/envs/indicbart/lib/python3.6/site-packages/transformers/generation_utils.py", line 379, in _prepare_encoder_decoder_kwargs_for_generation
    model_kwargs["encoder_outputs"]: ModelOutput = encoder(input_ids, return_dict=True, **encoder_kwargs)
  File "/home2/shivprasad.sagare/miniconda3/envs/indicbart/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'additional_input_ids'
```

**Comment by prajdabre** [comment]
Hi,

Please take a look at this and check if it helps.

https://github.com/prajdabre/yanmtt/issues/18#issuecomment-1079611610

**Comment by ShivprasadSagare** [comment]
Worked. Thank you.
